workflows:
  react-native-android:
    name: Bundle Fix Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    environment:
      groups:
        - env
      node: 18
      java: 17
    scripts:
      - name: Build with Proper JS Bundle
        script: |
          npm install -g @expo/cli@latest
          
          cat > package.json << 'EOF'
          {
            "name": "untold",
            "version": "1.0.0",
            "main": "index.js",
            "scripts": {
              "start": "expo start",
              "android": "expo start --android"
            },
            "dependencies": {
              "expo": "~51.0.28",
              "react": "18.2.0",
              "react-native": "0.74.5"
            }
          }
          EOF
          
          cat > index.js << 'EOF'
          import { registerRootComponent } from 'expo';
          import App from './App';
          registerRootComponent(App);
          EOF
          
          cat > App.js << 'EOF'
          import React from 'react';
          import { Text, View } from 'react-native';
          
          export default function App() {
            return (
              <View style={{
                flex: 1,
                justifyContent: 'center',
                alignItems: 'center',
                backgroundColor: '#667eea'
              }}>
                <Text style={{
                  fontSize: 24,
                  color: 'white',
                  fontWeight: 'bold',
                  textAlign: 'center'
                }}>
                  🎉 Untold App 🎉{'\n'}
                  Share & Heal{'\n'}
                  Working Successfully!
                </Text>
              </View>
            );
          }
          EOF
          
          cat > app.json << 'EOF'
          {
            "expo": {
              "name": "Untold",
              "slug": "untold",
              "version": "1.0.0",
              "platforms": ["android"],
              "android": {
                "package": "com.untold.app",
                "versionCode": 2
              },
              "plugins": []
            }
          }
          EOF
          
          npm install
          npx expo prebuild --platform android --clean
          
          cd android
          chmod +x gradlew
          
          cat > gradle.properties << 'EOF'
          org.gradle.jvmargs=-Xmx3072m
          android.useAndroidX=true
          android.enableJetifier=true
          hermesEnabled=false
          newArchEnabled=false
          
          # Bundle settings to fix script loading
          org.gradle.parallel=true
          org.gradle.daemon=true
          EOF
          
          # Fix hermesEnabled references
          sed -i 's/hermesEnabled/false/g' app/build.gradle
          
          # Add required resources
          mkdir -p app/src/main/res/values
          mkdir -p app/src/main/res/drawable
          mkdir -p app/src/main/assets
          
          cat > app/src/main/res/values/colors.xml << 'EOF'
          <?xml version="1.0" encoding="utf-8"?>
          <resources>
              <color name="splashscreen_background">#667eea</color>
              <color name="colorPrimary">#667eea</color>
              <color name="colorPrimaryDark">#5a6fd8</color>
              <color name="colorAccent">#667eea</color>
          </resources>
          EOF
          
          cat > app/src/main/res/drawable/splashscreen.xml << 'EOF'
          <?xml version="1.0" encoding="utf-8"?>
          <layer-list xmlns:android="http://schemas.android.com/apk/res/android">
              <item android:drawable="@color/splashscreen_background" />
          </layer-list>
          EOF
          
          # Force bundle to be included in APK
          echo "Creating JavaScript bundle..."
          cd ..
          npx expo export --platform android --output-dir dist
          
          # Copy bundle to Android assets
          if [ -d "dist/_expo/static/js" ]; then
            cp dist/_expo/static/js/*.js android/app/src/main/assets/ || echo "No JS files to copy"
          fi
          
          cd android
          
          # Ensure bundle is properly referenced
          sed -i 's/minifyEnabled true/minifyEnabled false/g' app/build.gradle
          sed -i 's/shrinkResources true/shrinkResources false/g' app/build.gradle
          
          # Build release APK for better bundle packaging
          echo "Building release APK with bundled JavaScript..."
          ./gradlew clean
          ./gradlew assembleRelease
          
          APK=$(find . -name "*release*.apk" | head -1)
          if [ -n "$APK" ]; then
            cp "$APK" ../UntoldApp-Bundled.apk
            echo "✅ Bundled APK created: UntoldApp-Bundled.apk"
            ls -lh ../UntoldApp-Bundled.apk
            
            # Upload
            UPLOAD_RESULT=$(curl -F "file=@../UntoldApp-Bundled.apk" https://file.io)
            DOWNLOAD_LINK=$(echo "$UPLOAD_RESULT" | grep -o '"link":"[^"]*"' | cut -d'"' -f4)
            
            cat > ../BUNDLE_FIXED.txt << EOF
          🔧 UNTOLD APP - BUNDLE FIXED! 🔧
          
          📱 File: UntoldApp-Bundled.apk
          📊 Size: $(ls -lh ../UntoldApp-Bundled.apk | awk '{print $5}')
          🔧 Fixed: JavaScript bundle loading issue
          📦 Type: Release APK with embedded bundle
          
          📥 DOWNLOAD:
          $DOWNLOAD_LINK
          
          ⚠️ INSTALLATION:
          1. Uninstall the old Untold app completely
          2. Clear cache/restart phone
          3. Install this new version
          4. Should work without script errors!
          
          🚀 BUNDLE ISSUE RESOLVED! 🚀
          EOF
            
            echo "=============================================="
            cat ../BUNDLE_FIXED.txt
            echo "=============================================="
            
          else
            echo "❌ Release build failed, trying debug..."
            ./gradlew assembleDebug
            APK=$(find . -name "*debug*.apk" | head -1)
            if [ -n "$APK" ]; then
              cp "$APK" ../UntoldApp-Debug-Bundled.apk
              echo "✅ Debug APK created as fallback"
            fi
          fi
    
    artifacts:
      - UntoldApp-Bundled.apk
      - UntoldApp-Debug-Bundled.apk
      - BUNDLE_FIXED.txt
    
    publishing:
      email:
        recipients:
          - skbad911@gmail.com
        notify:
          success: true
          failure: true