workflows:
  react-native-android:
    name: Untold App - Kotlin Fix
    max_build_duration: 120
    instance_type: mac_mini_m1
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    environment:
      groups:
        - env
      node: 18
      java: 17
    scripts:
      - name: Install dependencies
        script: |
          npm cache clean --force
          npm install
      
      - name: Install Expo CLI
        script: |
          npm install -g @expo/cli@latest
          npx expo --version
      
      - name: Create minimal app.json without problematic plugins
        script: |
          cat > app.json << 'EOF'
          {
            "expo": {
              "name": "UntoldApp",
              "slug": "untold-app",
              "version": "1.0.0",
              "android": {
                "package": "com.untold.shareapp",
                "versionCode": 1
              },
              "plugins": []
            }
          }
          EOF
          echo "Created minimal app.json without expo-router:"
          cat app.json
      
      - name: Create basic app structure
        script: |
          # Create basic React Native structure instead of expo-router
          mkdir -p src
          cat > App.tsx << 'EOF'
          import React from 'react';
          import { Text, View, StyleSheet } from 'react-native';
          
          export default function App() {
            return (
              <View style={styles.container}>
                <Text style={styles.text}>Welcome to Untold App!</Text>
              </View>
            );
          }
          
          const styles = StyleSheet.create({
            container: {
              flex: 1,
              justifyContent: 'center',
              alignItems: 'center',
              backgroundColor: '#fff',
            },
            text: {
              fontSize: 18,
              fontWeight: 'bold',
            },
          });
          EOF
          
          # Remove expo-router related files that might cause Kotlin compilation issues
          rm -rf app/
      
      - name: Prebuild with minimal config
        script: |
          rm -rf android ios .expo
          npx expo prebuild --platform android --clean --no-install
          
          echo "Checking generated android structure:"
          ls -la android/
          ls -la android/app/src/main/java/ || echo "No java folder"
      
      - name: Fix Kotlin compilation issues
        script: |
          cd android
          
          # Set specific Kotlin version that's known to work
          cat > gradle.properties << 'EOF'
          # Gradle properties
          org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=512m
          org.gradle.parallel=true
          org.gradle.daemon=true
          
          # Android properties
          android.useAndroidX=true
          android.enableJetifier=true
          android.defaults.buildfeatures.buildconfig=true
          android.nonTransitiveRClass=false
          android.enableR8.fullMode=false
          
          # Kotlin version fix
          kotlin.version=1.8.22
          EOF
          
          # Update root build.gradle to use compatible Kotlin version
          if [ -f "build.gradle" ]; then
            echo "Updating root build.gradle..."
            sed -i.bak 's/kotlin("android") version "[^"]*"/kotlin("android") version "1.8.22"/g' build.gradle
            sed -i.bak 's/kotlin_version = "[^"]*"/kotlin_version = "1.8.22"/g' build.gradle
            
            # Also ensure buildscript has correct version
            sed -i.bak 's/id "org.jetbrains.kotlin.android" version "[^"]*"/id "org.jetbrains.kotlin.android" version "1.8.22"/g' build.gradle
            
            echo "Modified build.gradle:"
            head -30 build.gradle
          fi
          
          # Update app build.gradle
          if [ -f "app/build.gradle" ]; then
            echo "Checking app/build.gradle..."
            # Disable any problematic features
            sed -i.bak 's/minifyEnabled true/minifyEnabled false/g' app/build.gradle
            sed -i.bak 's/shrinkResources true/shrinkResources false/g' app/build.gradle
          fi
          
          chmod +x ./gradlew
      
      - name: Clean and test Kotlin compilation
        script: |
          cd android
          echo "Cleaning project..."
          ./gradlew clean
          
          echo "Testing Kotlin compilation with specific task..."
          ./gradlew compileDebugKotlin --stacktrace --info || echo "Kotlin compilation failed, continuing..."
      
      - name: Build debug APK
        script: |
          cd android
          echo "Building debug APK..."
          ./gradlew assembleDebug --stacktrace --info
          
          echo "Checking outputs:"
          find app/build/outputs -name "*.apk" -type f || echo "No APK found"
    
    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/app/build/logs/**/*
    
    publishing:
      email:
        recipients:
          - skbad911@gmail.com
        notify:
          success: true
          failure: true