workflows:
  react-native-android:
    name: Untold App - Android APK
    max_build_duration: 120
    instance_type: mac_mini_m1
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    environment:
      groups:
        - env
      node: 18
      java: 17
    scripts:
      - name: Check environment
        script: |
          echo "Node version: $(node --version)"
          echo "NPM version: $(npm --version)"
          echo "Java version: $(java -version)"
          echo "Project files:"
          ls -la
      
      - name: Install dependencies
        script: |
          npm cache clean --force
          npm install
      
      - name: Install Expo CLI
        script: |
          npm install -g @expo/cli@latest
          npx expo --version
      
      - name: Create super minimal app.json
        script: |
          cat > app.json << 'EOF'
          {
            "expo": {
              "name": "UntoldApp",
              "slug": "untold-app",
              "version": "1.0.0",
              "android": {
                "package": "com.untold.shareapp"
              },
              "plugins": ["expo-router"]
            }
          }
          EOF
          echo "Created minimal app.json:"
          cat app.json
      
      - name: Clean and prebuild
        script: |
          rm -rf android ios .expo
          echo "Running prebuild..."
          npx expo prebuild --platform android --clean --no-install
          echo "Prebuild completed. Checking android folder:"
          ls -la android/
      
      - name: Configure Gradle
        script: |
          cd android
          echo "Adding basic gradle properties..."
          echo "org.gradle.jvmargs=-Xmx4096m" >> gradle.properties
          echo "android.useAndroidX=true" >> gradle.properties
          echo "android.enableJetifier=true" >> gradle.properties
          chmod +x ./gradlew
      
      - name: Clean Gradle
        script: |
          cd android
          ./gradlew clean
      
      - name: Test Gradle build
        script: |
          cd android
          echo "Testing basic gradle build..."
          ./gradlew tasks --all | head -20
          echo "Attempting debug build..."
          ./gradlew assembleDebug --stacktrace
    
    artifacts:
      - android/app/build/outputs/**/*.apk
    
    publishing:
      email:
        recipients:
          - skbad911@gmail.com
        notify:
          success: true
          failure: true