workflows:
  react-native-android:
    name: Hermes Fix Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    environment:
      groups:
        - env
      node: 18
      java: 17
    scripts:
      - name: Quick setup
        script: |
          npm cache clean --force
          npm install
          npm install -g @expo/cli@latest
          
          cat > app.json << 'EOF'
          {
            "expo": {
              "name": "UntoldApp",
              "slug": "untold-app",
              "version": "1.0.0",
              "android": {
                "package": "com.untold.shareapp",
                "versionCode": 1
              },
              "plugins": [
                [
                  "expo-build-properties",
                  {
                    "android": {
                      "enableHermes": true
                    }
                  }
                ]
              ]
            }
          }
          EOF
          
          cat > App.tsx << 'EOF'
          import React from 'react';
          import { Text, View, StyleSheet } from 'react-native';
          
          export default function App() {
            return (
              <View style={styles.container}>
                <Text style={styles.text}>🎉 Untold App - Share & Heal 🎉</Text>
                <Text style={styles.subtitle}>Your journey starts here!</Text>
              </View>
            );
          }
          
          const styles = StyleSheet.create({
            container: {
              flex: 1,
              justifyContent: 'center',
              alignItems: 'center',
              backgroundColor: '#667eea',
            },
            text: {
              fontSize: 24,
              fontWeight: 'bold',
              color: 'white',
              textAlign: 'center',
              marginBottom: 20,
            },
            subtitle: {
              fontSize: 16,
              color: 'white',
              textAlign: 'center',
            },
          });
          EOF
          
          rm -rf app/ android ios .expo
      
      - name: Prebuild and fix Hermes
        script: |
          npx expo prebuild --platform android --clean --no-install
          
          cd android
          
          echo "=== Fixing Hermes configuration in app/build.gradle ==="
          # Fix the hermesEnabled property issue
          sed -i.bak 's/hermesEnabled/enableHermes/g' app/build.gradle
          
          # Also ensure Hermes is properly defined
          sed -i.bak '/enableHermes.*=/d' app/build.gradle
          sed -i.bak '/project.ext.react/a\
          def enableHermes = project.ext.react.get("enableHermes", true)' app/build.gradle
          
          echo "=== Checking app/build.gradle for Hermes references ==="
          grep -n -A 5 -B 5 "ermes" app/build.gradle || echo "No Hermes references found"
          
          echo "=== Setting up gradle.properties ==="
          cat > gradle.properties << 'EOF'
          org.gradle.jvmargs=-Xmx4096m
          android.useAndroidX=true
          android.enableJetifier=true
          kotlin.version=1.8.22
          
          # React Native specific
          FLIPPER_VERSION=0.201.0
          reactNativeArchitectures=armeabi-v7a,arm64-v8a,x86,x86_64
          newArchEnabled=false
          hermesEnabled=true
          EOF
          
          chmod +x ./gradlew
      
      - name: Build and upload APK
        script: |
          cd android
          
          echo "=== Cleaning project ==="
          ./gradlew clean
          
          echo "=== Building debug APK ==="
          ./gradlew assembleDebug --stacktrace --info
          
          echo "=== Searching for APK ==="
          APK_FILE=$(find . -name "*.apk" -type f | head -1)
          
          if [ -n "$APK_FILE" ]; then
            echo "✅ Found APK: $APK_FILE"
            APK_SIZE=$(ls -lh "$APK_FILE" | awk '{print $5}')
            echo "📱 APK Size: $APK_SIZE"
            
            # Rename APK with timestamp
            TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
            NEW_NAME="UntoldApp_${TIMESTAMP}.apk"
            cp "$APK_FILE" "../$NEW_NAME"
            
            echo "=== Uploading to cloud services ==="
            
            # Upload to file.io
            echo "📤 Uploading to file.io..."
            UPLOAD_RESPONSE=$(curl -F "file=@../$NEW_NAME" https://file.io)
            echo "Upload Response: $UPLOAD_RESPONSE"
            
            # Extract download link
            DOWNLOAD_LINK=$(echo "$UPLOAD_RESPONSE" | grep -o '"link":"[^"]*"' | cut -d'"' -f4)
            
            # Upload to transfer.sh as backup
            echo "📤 Uploading to transfer.sh..."
            TRANSFER_LINK=$(curl --upload-file "../$NEW_NAME" https://transfer.sh/$NEW_NAME)
            
            # Create download summary
            cat > ../SUCCESS_DOWNLOAD.txt << EOF
          🎉🎉🎉 UNTOLD APP BUILD SUCCESSFUL! 🎉🎉🎉
          
          📱 APK: $NEW_NAME
          📊 Size: $APK_SIZE
          📅 Built: $(date)
          
          📥 DOWNLOAD LINKS:
          Primary: $DOWNLOAD_LINK
          Backup:  $TRANSFER_LINK
          
          📱 TO INSTALL:
          1. Download APK using either link above
          2. Enable "Unknown sources" on Android
          3. Install the APK file
          4. Launch Untold App!
          
          🚀 ENJOY YOUR APP! 🚀
          EOF
            
            echo ""
            echo "=================================================="
            cat ../SUCCESS_DOWNLOAD.txt
            echo "=================================================="
            
          else
            echo "❌ No APK file found after build!"
            echo "Checking build outputs:"
            find . -path "*/outputs/*" -type f 2>/dev/null || echo "No output files found"
          fi
    
    artifacts:
      - "*.apk"
      - SUCCESS_DOWNLOAD.txt
    
    publishing:
      email:
        recipients:
          - skbad911@gmail.com
        notify:
          success: true
          failure: true