workflows:
  react-native-android:
    name: Untold App - Android APK
    max_build_duration: 60
    instance_type: mac_mini_m1
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    environment:
      groups:
        - env
      node: 18
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm uninstall expo-permissions --no-save
      - name: Install Expo CLI
        script: |
          npm install -g @expo/cli
      - name: Expo prebuild
        script: |
          npx expo prebuild --platform android --clean
      - name: Build Android APK
        script: |
          cd android
          chmod +x ./gradlew
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/app/build/outputs/**/mapping.txt
    publishing:
      email:
        recipients:
          - skbad911@gmail.com
        notify:
          success: true
          failure: true