workflows:
  react-native-android:
    name: Untold App - Android APK
    max_build_duration: 60
    instance_type: mac_mini_m1
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    environment:
      groups:
        - env
      node: 18
      java: 17
    scripts:
      - name: Check files
        script: |
          echo "Checking project structure..."
          ls -la
          cat package.json | head -20
          cat app.json | head -30
      
      - name: Install dependencies
        script: |
          npm cache clean --force
          npm ci
      
      - name: Install Expo CLI
        script: |
          npm install -g @expo/cli@latest
      
      - name: Remove old builds
        script: |
          rm -rf android ios .expo
      
      - name: Fix app.json before prebuild
        script: |
          echo "Original app.json content:"
          cat app.json
          # Remove the kotlinVersion line completely
          sed -i.bak 's/"kotlinVersion": "1.9.24",//g' app.json
          sed -i.bak 's/"kotlinVersion": "1.9.24"//g' app.json
          echo "Modified app.json content:"
          cat app.json
      
      - name: Prebuild Android
        script: |
          npx expo prebuild --platform android --clean --no-install
      
      - name: Force Kotlin version in Gradle
        script: |
          cd android
          # Add Kotlin version to gradle.properties
          echo "kotlin.version=1.9.10" >> gradle.properties
          echo "android.defaults.buildfeatures.buildconfig=true" >> gradle.properties
          echo "android.nonTransitiveRClass=false" >> gradle.properties
          echo "android.enableJetifier=true" >> gradle.properties
          echo "android.useAndroidX=true" >> gradle.properties
          
          # Force Kotlin version in root build.gradle
          sed -i.bak 's/kotlin("android") version "1.9.24"/kotlin("android") version "1.9.10"/g' build.gradle
          sed -i.bak 's/kotlin_version = "1.9.24"/kotlin_version = "1.9.10"/g' build.gradle
          
          echo "Modified gradle.properties:"
          cat gradle.properties
          echo "Modified build.gradle:"
          cat build.gradle | head -50
      
      - name: Set Gradle permissions
        script: |
          cd android
          chmod +x ./gradlew
      
      - name: Clean Gradle
        script: |
          cd android
          ./gradlew clean --stacktrace
      
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleRelease --no-daemon --stacktrace --info
    
    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/app/build/outputs/**/mapping.txt
    
    publishing:
      email:
        recipients:
          - skbad911@gmail.com
        notify:
          success: true
          failure: true