workflows:
  react-native-android:
    name: Simple Basic Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    environment:
      groups:
        - env
      node: 18
      java: 17
    scripts:
      - name: Build APK
        script: |
          npm install -g @expo/cli@latest
          
          cat > package.json << 'EOF'
          {
            "name": "untold",
            "version": "1.0.0",
            "main": "App.js",
            "dependencies": {
              "expo": "~50.0.0",
              "react": "18.2.0",
              "react-native": "0.73.6"
            }
          }
          EOF
          
          cat > App.js << 'EOF'
          import React from 'react';
          import { Text, View } from 'react-native';
          
          export default function App() {
            return (
              <View style={{flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: '#667eea'}}>
                <Text style={{fontSize: 24, color: 'white', fontWeight: 'bold'}}>Untold App</Text>
              </View>
            );
          }
          EOF
          
          cat > app.json << 'EOF'
          {
            "expo": {
              "name": "Untold",
              "slug": "untold",
              "version": "1.0.0",
              "android": {
                "package": "com.untold.app"
              }
            }
          }
          EOF
          
          npm install
          npx expo prebuild --platform android --clean
          
          cd android
          chmod +x gradlew
          
          # Fix the bundle loading issue
          echo "react.gradle.bundleAssetName=index.android.bundle" >> gradle.properties
          
          ./gradlew assembleDebug
          
          APK=$(find . -name "*.apk" | head -1)
          if [ -n "$APK" ]; then
            cp "$APK" ../app.apk
            echo "APK created"
            curl --upload-file ../app.apk https://file.io
          fi
    
    artifacts:
      - app.apk