workflows:
  react-native-android:
    name: Simple Working Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    environment:
      groups:
        - env
      node: 18
      java: 17
    scripts:
      - name: Build APK
        script: |
          npm install -g @expo/cli@latest
          
          cat > package.json << 'EOF'
          {
            "name": "untold",
            "version": "1.0.0",
            "main": "App.js",
            "dependencies": {
              "expo": "~51.0.28",
              "react": "18.2.0",
              "react-native": "0.74.5"
            }
          }
          EOF
          
          cat > App.js << 'EOF'
          import React from 'react';
          import { Text, View } from 'react-native';
          
          export default function App() {
            return (
              <View style={{flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: '#667eea'}}>
                <Text style={{fontSize: 24, color: 'white', fontWeight: 'bold'}}>Untold App</Text>
              </View>
            );
          }
          EOF
          
          cat > app.json << 'EOF'
          {
            "expo": {
              "name": "Untold",
              "slug": "untold",
              "version": "1.0.0",
              "android": {
                "package": "com.untold.app"
              }
            }
          }
          EOF
          
          npm install
          npx expo prebuild --platform android --clean
          
          cd android
          chmod +x gradlew
          
          cat > gradle.properties << 'EOF'
          org.gradle.jvmargs=-Xmx4096m
          android.useAndroidX=true
          android.enableJetifier=true
          hermesEnabled=true
          EOF
          
          # Fix hermesEnabled error in app/build.gradle
          sed -i 's/hermesEnabled/project.findProperty("hermesEnabled") ?: true/g' app/build.gradle
          
          # Fix splash screen resource error
          mkdir -p app/src/main/res/values
          cat > app/src/main/res/values/colors.xml << 'EOF'
          <?xml version="1.0" encoding="utf-8"?>
          <resources>
              <color name="splashscreen_background">#667eea</color>
          </resources>
          EOF
          
          # Remove problematic splash screen file if it exists
          rm -f app/src/main/res/drawable/splashscreen.xml
          
          ./gradlew assembleDebug
          
          APK=$(find . -name "*.apk" | head -1)
          if [ -n "$APK" ]; then
            cp "$APK" ../app.apk
            echo "APK created: app.apk"
            curl --upload-file ../app.apk https://transfer.sh/app.apk
          else
            echo "No APK found"
          fi
    
    artifacts:
      - app.apk
    
    publishing:
      email:
        recipients:
          - skbad911@gmail.com
        notify:
          success: true
          failure: true